name: Publish (pypi)

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          bash ./dev/setup.sh --deps "development"
      - name: Publish
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.PYPI_API_TOKEN }}"
        run: |
          bash dev/publish.sh "pypi"
      # It takes some time when the package gets available.
      - name: Sleep
        run: |
          sleep 120

  test-published-package:
    needs:
      - publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install package
        env:
          PACKAGE_NAME: "lightdash-ops"
        run: |
          python -m pip install -U "${{ env.PACKAGE_NAME }}"
