name: Test publish (testpypi)

on:
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      package_version:
        description: package version
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          bash ./dev/setup.sh --deps "development"
      - name: Test publish
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.TESTPYPI_API_TOKEN }}"
          PACKAGE_VERSION: "${{ inputs.package_version }}"
        run: |
          uv run bash dev/publish.sh testpypi
      # It takes some time when the package gets available.
      - name: Sleep
        run: |
          sleep 120

  test-published-package:
    needs:
      - publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install packages
        env:
          PACKAGE_NAME: lightdash-ops
          PACKAGE_VERSION: "${{ inputs.package_version }}"
        run: |
          python -m pip install -U pip
          # shellcheck disable=SC1009,SC1072,SC1073
          python -m pip install \
            --index-url "https://test.pypi.org/simple/" \
            --extra-index-url "https://pypi.org/simple/" \
            -U "${{ env.PACKAGE_NAME }}=="${{ env.PACKAGE_VERSION }}"
      - name: Show packages
        run: |
          pip list
